name: CI/CD

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install jshint --global
      - run: |
          find ./giftlink-backend -name '*.js' -exec jshint {} +
          echo "Linted all JS files successfully"

  client_build:
    name: Build client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          cd giftlink-frontend
          npm install
          npm run build
          echo "Client-side build successfully"